name: Work 1 Ferdinand
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Primera Impresion
        run: echo "Impresion 1"
      - name: Segunda Impresion
        run: echo "Impresion 2"
      - name: Tercera Impresion
        run: echo "Impresion 3"